### PR TITLE
[#20] Update documentation for logging library (main)

### PR DESCRIPTION
**Pull request by korydraughn**
@trel What is the iteration process for this?

I made changes before standing everything up and those were visible in the browser. Since then, I've made additional changes but those don't appear at all. I've tried restarting the httpd server and that didn't work.

I feel like something has been cached.

### CODE REVIEW

**Comment by trel** [comment]
The irods/irods code and the doxgen downloads are cached.

Any changes to docs should get put into the docker container if you rebuild it.

**Comment by korydraughn** [comment]
When I make changes, how should I rebuild it?

I tried running `docker run --rm -v $(pwd)/build:/hostcomputer irods_docs_builder`, but it didn't work for me.

**Comment by trel** [comment]
Re-run the build step.

This is the line that gets the new files into the container:
https://github.com/irods/irods_docs/blob/main/Dockerfile#L44

Happy to be told a better way... @alanking ?

**Comment by korydraughn** [comment]
I think we have to pull that out of the image building step and provide irods_docs via a volume mount. It avoids producing several images due to the iteration process and results in an image that only contains the tools to build the docs.

I'll give that a try.

**Review by alanking — APPROVED** [review]
Looks good. I'll wait for input from @trel before proceeding.

I created #129 for the Github Actions failure.

**Comment by korydraughn** [comment]
Sure. I may look into fixing #129 since I'm already here.

**Comment by korydraughn** [comment]
Something is clearly wrong with the github actions when it tries to compile doxygen. The compiler seems to fail in a weird way.

**Comment by korydraughn** [comment]
Turns out building doxygen used too many resources. Removing `-j` from the doxygen build step allowed the github action to work.

I've updated the project so that the value to `-j` is configurable.

**Comment by korydraughn** [comment]
Any last thoughts/concerns before I add the #'s?

**Comment by korydraughn** [comment]
Any last thoughts/concerns before I add the #'s?

**Comment by trel** [comment]
seems good

**Pull request merged**
