### PR TITLE
Documented missing specific query, DataObjInCollReCur, for MySQL (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
seems good

**Comment by korydraughn** [comment]
Going to test and make sure that copying the command works as expected. If it does, I'll add the pound.

**Comment by korydraughn** [comment]
I've verified that the command in the documentation works.

I had to modify the testing environment so that it would stand up a 4.2.11 server backed by MySQL 8 (basically had to change the collation and charset settings - PR will come soon).

Adding pound.

**Comment by korydraughn** [comment]
#'d

**Comment by korydraughn** [comment]
This may not be doable for 4.2.

As of right now, 4.2 setup fails against MySQL 8 unless the collation and charset are changed to something that doesn't cause the **row size too large** error. Otherwise, the admin must modify the database schema in a way that isn't supported by the 4.2 server.

**Review by trel — APPROVED** [review]
this seems correct

**Comment by korydraughn** [comment]
Good. Will squash and pound shortly.

**Comment by korydraughn** [comment]
Added pounds.

**Pull request merged**
