### PR TITLE
[#252] Add section describing rules for including TODO comments (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Still need to render the text to see what it looks like.

### CODE REVIEW

**Review by trel — APPROVED** [review]
seems good

**Comment by korydraughn** [comment]
squashing

**Comment by korydraughn** [comment]
Squashed.

**Comment by trel** [comment]
if it rendered as you want - # it.

**Comment by korydraughn** [comment]
Removed the part from the third item stating developer name can be derived from VCS.

Pounding now.

**Comment by korydraughn** [comment]
#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
