### PR TITLE
[#134] Development docs: update branch names (main)

### PR DESCRIPTION
**Pull request by stsnel**

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good.

Please link the commit to issue number 134 (without the pound). That way we can make sure everything looks good before approving and pounding.

**Review by alanking — APPROVED** [review]
Looks good to me. \# it!

**Comment by korydraughn** [comment]
Merging!

**Comment by korydraughn** [comment]
@stsnel Thanks for the contribution :-)

**Pull request merged**
