### PR TITLE
[#7575] Update docs for dynamic PEPs (main)

### PR DESCRIPTION
**Pull request by korydraughn**
I think I got all of the newer APIs. If I missed one, let me know.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Seems good to me. Should we wait until https://github.com/irods/irods/pull/7582 is merged before we merge this, just in case?

**Comment by korydraughn** [comment]
Yes.

**Review by alanking — COMMENTED** [review]
Seems good to me. Squash?

Don't forget to update the issue link to point to the other repo (e.g. irods/irods#7575)

**Comment by korydraughn** [comment]
Squashed. No #'s.

**Review by alanking — APPROVED** [review]
I say we # it.

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
