### PR TITLE
[irods/irods#7382] Fix installation instructions for Postgres 15+

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7382

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Seems good to me. Do these instructions work for older versions of Postgres? No is okay, but perhaps we should mention the minimum version somewhere... Or even put the old instructions in a separate section?

**Comment by SwooshyCueb** [comment]
Yes, this works for older versions as well

**Review by alanking — APPROVED** [review]
Nice. # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
