### PR TITLE
[irods/irods#4904] irodsPamAuthCheck: Add more docs (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses irods/irods#4904

My understanding is that we have no plans to update irodsPamAuthCheck itself. If anything, we would write a different tool for use in the future if we wanted to make any changes.

Also, happy to squash down to one if we're into it.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Very nice. Pound when ready.

**Comment by korydraughn** [comment]
Your second commit message about the heading needs a tweak.

`so this commit move the` -> `so this commit moves the`

**Comment by alanking** [comment]
Good catch. I've amended the commit message and squashed to one.

**Review by korydraughn — APPROVED** [review]
Ship it.

**Pull request merged**
