### PR TITLE
[irods/irods#6719] Add note about overwrite behavior of unattended installations (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Here's a rendering of the text.

image

### CODE REVIEW

**Comment by trel** [comment]
Diff looks fine

**Comment by korydraughn** [comment]
The image isn't appearing?

**Comment by korydraughn** [comment]
It renders on my phone and when using incognito mode.

**Comment by trel** [comment]
Not on phone.   Open in a new browser?

**Comment by trel** [comment]
Not a blocker.

**Comment by korydraughn** [comment]
Pounded/Merging.

**Pull request merged**
